### PR TITLE
Go Back to the old text editor.

### PR DESCRIPTION
**Pull request by I-AQ**

### CODE REVIEW

**Comment by I-AQ** [comment]
Due to some problems I switch back to the original text editor. 
Warning: This version has not been tested.

**Comment by AzhamProdLive** [comment]
Push on Alpha branch or the dev branch instead of the beta one then, will be safer.

**Comment by AzhamProdLive** [comment]
(if it's not properly tested ofc, so we can test it)

**Comment by I-AQ** [comment]
But there is no alpha/dev branch. Should I just create a new one?

**Comment by AzhamProdLive** [comment]
Just made one, named Alpha Builds

**Pull request closed without merging**
